public with sharing class Anonima {
    public Anonima() {

    }
}

/*
List<String> lista = new List<String>();
lista.add('abacate');
lista.add('manga');
lista.add('laranja');
lista.add('uva');
System.debug(lista[4]);




String [] lista = new List<String>();
lista.add('abacate');
lista.add('manga');
lista.add('laranja');
lista.add('uva');

System.debug(lista[0]);





//Array ou Vetor
String [] vetorDePalavras = new String[11];
vetorDePalavras[0] = 'abacate';
vetorDePalavras[1] = 'manga';
vetorDePalavras[3] = 'morango';
vetorDePalavras[4] = 'mamão';
vetorDePalavras[5] = 'uva';
vetorDePalavras[6] = 'melão';
vetorDePalavras[7] = 'melancia';
vetorDePalavras[8] = 'kiwi';
vetorDePalavras[9] = 'banana';


//for each
String texto = '';
for(String fruta:vetorDePalavras){
    if(fruta != null){
        texto += fruta + ', ';
        //System.debug('Palavra: ' + fruta);
    }
}
System.debug(texto);


System.debug((fruta!=null)?'Palavra: ' + fruta:'');








Integer tamanhoDoVetor = vetorDePalavras.size();
for(Integer i=0;i<tamanhoDoVetor;i++){
    //System.debug('i vale: ' + i);
    // if(vetorDePalavras[i] != null){
        System.debug('Palavra: ' + vetorDePalavras[i]);
    // }
}
System.debug('Código fora do loop');




//Loop

//while
//do while
//for
//for each

//iteração

Integer i = 0;
while(i < 10){
    System.debug('i vale: ' + i);
    i+=2;
}
System.debug('Código fora do loop');

Integer i = 10;
do{
    System.debug('i vale: ' + i);
    i+=1;
}while(i < 10);

for(Integer i=9;i>=0;i--){
    System.debug('i vale: ' + i);
}
System.debug('Código fora do loop');

*/