public with sharing class chaveamento {
    public chaveamento() {

    }
}


/*
String fruta = 'abacate';
switch on fruta {
    when 'abacate', 'manga' {
        System.debug('A fruta é: '+fruta);
    }
    when null {
        System.debug('X vale: null');
    }
    when 'maçã' {
        System.debug('A fruta é: '+fruta);
    }
    when else {
        System.debug('X não corresponde a nenhum valor');
    }
}*/
    

